/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,
  ScrollView,
  Image,
  Linking,
  Dimensions,
  TouchableOpacity,
} from 'react-native';
import {
  ClipboardContext,
  ClipboardProvider,
} from 'react-native-media-clipboard';

const ClipboardUse = () => {
  const {clipboard, mediaSource} = React.useContext(ClipboardContext);

  return (
    <View style={{flex: 1, paddingTop: 100, paddingHorizontal: 20}}>
      <ScrollView style={{height: '100%'}}>
        {clipboard.hasImages ? (
          <Image
            source={mediaSource}
            style={{
              width: Dimensions.get('screen').width - 40,
              height: Dimensions.get('screen').width - 40,
              marginVertical: 40,
            }}
            resizeMode="contain"
          />
        ) : (
          <View
            style={{
              width: Dimensions.get('screen').width - 40,
              height: Dimensions.get('screen').width / 2,
              paddingVertical: 40,
              justifyContent: 'center',
              backgroundColor: '#eee',
              borderRadius: 12,
              overflow: 'hidden',
              alignItems: 'center',
            }}>
            <Text
              textAlign="center"
              style={{textAlign: 'center', flex: 0, marginLeft: -20}}>
              No image in clipboard.
            </Text>
          </View>
        )}

        <View
          style={{
            marginVertical: 14,
            width: '100%',
            backgroundColor: '#999',
            flex: 0,
            height: 1,
          }}
        />

        {clipboard.hasStrings && (
          <>
            <View style={{paddingVertical: 4}}>
              <Text>Strings:</Text>
              <View style={{paddingVertical: 10}}>
                {clipboard.strings.map((string, index) => (
                  <View key={`${string}-index`} style={{flexDirection: 'row'}}>
                    <View style={{marginRight: 8}}>
                      <Text style={{fontFamily: 'Courier'}}>Line {index}:</Text>
                    </View>
                    <Text style={{fontFamily: 'Courier'}}>{string}</Text>
                  </View>
                ))}
              </View>
            </View>
            <View
              style={{
                marginVertical: 14,
                width: '100%',
                backgroundColor: '#999',
                flex: 0,
                height: 1,
              }}
            />
          </>
        )}

        {clipboard.urls.length > 0 && (
          <>
            <View style={{paddingVertical: 4}}>
              <Text>URLs:</Text>
              <View style={{paddingHorizontal: 12, marginVertical: 8}}>
                {clipboard.urls.map((string, index) => (
                  <TouchableOpacity
                    key={index}
                    onPress={() => Linking.openURL(string)}>
                    <View>
                      <Text
                        style={{
                          color: 'blue',
                          textDecorationLine: 'underline',
                        }}>
                        {string}
                      </Text>
                    </View>
                  </TouchableOpacity>
                ))}
              </View>
            </View>
            <View
              style={{
                marginVertical: 14,
                width: '100%',
                backgroundColor: '#999',
                flex: 0,
                height: 1,
              }}
            />
          </>
        )}

        <View>
          <Text style={{fontSize: 16, marginVertical: 2}}>
            ClipboardContext.clipboard:
          </Text>
        </View>
        <View style={{marginHorizontal: 12, paddingVertical: 12}}>
          <Text
            style={{
              fontFamily: 'Courier',
            }}>
            {JSON.stringify(clipboard, null, 2)}
          </Text>
        </View>
        <View>
          <Text style={{fontSize: 16, marginVertical: 4}}>
            ClipboardContext.mediaSource:
          </Text>
        </View>
        <View style={{marginHorizontal: 12, paddingVertical: 12}}>
          <Text
            style={{
              fontFamily: 'Courier',
            }}>
            {JSON.stringify(mediaSource, null, 2)}
          </Text>
        </View>
      </ScrollView>
    </View>
  );
};

export default class App extends React.Component {
  render() {
    return (
      <ClipboardProvider>
        <ClipboardUse />
      </ClipboardProvider>
    );
  }
}
